routes/web.php
<?php

use App\Http\Controllers\Auth\LoginController;
use App\Http\Controllers\Auth\RegisterController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\ProvinceController;
use App\Http\Controllers\Back\MainController;
use App\Http\Controllers\Back\UserController;
use App\Http\Controllers\Back\ProductController;
use App\Http\Controllers\Back\BrandController;
use App\Http\Controllers\Back\FilterController;
use App\Http\Controllers\Back\AttributeGroupController;
use App\Http\Controllers\Back\AttributeController;
use App\Http\Controllers\Back\BackupController;
use App\Http\Controllers\Back\SpecTypeController;
use App\Http\Controllers\Back\PostController;
use App\Http\Controllers\Back\CategoryController;
use App\Http\Controllers\Back\PageController;
use App\Http\Controllers\Back\MenuController;
use App\Http\Controllers\Back\OrderController;
use App\Http\Controllers\Back\ShippingCostController;
use App\Http\Controllers\Back\TransactionController;
use App\Http\Controllers\Back\SliderController;
use App\Http\Controllers\Back\BannerController;
use App\Http\Controllers\Back\LinkController;
use App\Http\Controllers\Back\ContactController;
use App\Http\Controllers\Back\StockNotifyController;
use App\Http\Controllers\Back\CommentController;
use App\Http\Controllers\Back\DeveloperController;
use App\Http\Controllers\Back\DiscountController;
use App\Http\Controllers\Back\InstallController;
use App\Http\Controllers\Back\RoleController;
use App\Http\Controllers\Back\PermissionController;
use App\Http\Controllers\Back\SettingController;
use App\Http\Controllers\Back\StatisticsController;
use App\Http\Controllers\Back\ThemeController;
use App\Http\Controllers\PushSubscriptionController;
use Rap2hpoutre\LaravelLogViewer\LogViewerController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group([], function () {
    // ------------------ Authentication Routes...
    Route::get('login', [LoginController::class, 'showLoginForm'])->name('login')->middleware('CheckUserExists');
    Route::post('login', [LoginController::class, 'login']);
    Route::post('logout', [LoginController::class, 'logout'])->name('logout');

    // ------------------ Registration Routes...
    Route::get('register', [RegisterController::class, 'showRegistrationForm'])->name('register');
    Route::post('register', [RegisterController::class, 'register']);
    Route::get('logout', [LoginController::class, 'logout']);
});

Route::get('province/get-cities', [ProvinceController::class, 'getCities']);

Route::group(['as' => 'admin.', 'prefix' => 'admin/' . config('general.admin_route_prefix'), 'middleware' => ['guest']], function () {
    Route::get('login', [MainController::class, 'login'])->middleware(['CheckUserExists'])->name('login');
    Route::get('register', [InstallController::class, 'showRegisterForm'])->name('register')->middleware(['CheckUserNotExists']);
    Route::post('register', [InstallController::class, 'register'])->name('register')->middleware(['CheckUserNotExists']);
});

// ------------------ Admin Part Routes
Route::group(['as' => 'admin.', 'prefix' => 'admin/' . config('general.admin_route_prefix'), 'middleware' => ['auth', 'Admin']], function () {

    // ------------------ MainController
    Route::get('/', [MainController::class, 'index'])->name('dashboard');
    Route::get('get-tags', [MainController::class, 'get_tags']);

    Route::get('notifications', [MainController::class, 'notifications'])->name('notifications');

    Route::get('file-manager', [MainController::class, 'fileManager'])->name('file-manager');
    Route::get('file-manager-iframe', [MainController::class, 'fileManagerIframe'])->name('file-manager-iframe');

    // ------------------ backups
    Route::get('backups', [BackupController::class, 'index'])->name('backups.index');
    Route::post('backups/create', [BackupController::class, 'create'])->name('backups.create');
    Route::get('backups/{backup}/download', [BackupController::class, 'download'])->name('backups.download');
    Route::delete('backups/{backup}', [BackupController::class, 'destroy'])->name('backups.destroy');

    // ------------------ users
    Route::resource('users', UserController::class);
    Route::get('users/export/excel', [UserController::class, 'export'])->name('users.export');
    Route::get('users/{user}/views', [UserController::class, 'views'])->name('users.views');
    Route::get('user/profile', [UserController::class, 'showProfile'])->name('user.profile.show');
    Route::put('user/profile', [UserController::class, 'updateProfile'])->name('user.profile.update');

    // ------------------ products
    Route::resource('products', ProductController::class)->except('show');
    Route::post('products/image-store', [ProductController::class, 'image_store']);
    Route::post('products/image-delete', [ProductController::class, 'image_delete']);
    Route::get('product/categories', [ProductController::class, 'categories'])->name('products.categories.index');
    Route::post('product/slug', [ProductController::class, 'generate_slug']);

    Route::get('product/prices', [ProductController::class, 'indexPrices'])->name('product.prices.index');
    Route::put('product/prices', [ProductController::class, 'updatePrices'])->name('product.prices.update');

    // ------------------ products
    Route::resource('discounts', DiscountController::class)->except(['show']);

    // ------------------ brands
    Route::resource('brands', BrandController::class)->except('show');
    Route::get('brands/ajax/get', [BrandController::class, 'ajax_get']);

    // ------------------ filters
    Route::resource('filters', FilterController::class)->except('show');

    // ------------------ attributeGroups
    Route::resource('attributeGroups', AttributeGroupController::class);
    Route::get('attributeGroups/{attributeGroup}/attributes', [AttributeGroupController::class, 'attributesIndex'])->name('attributes.index');
    Route::post('attributeGroup/sort', [AttributeGroupController::class, 'sort']);

    // ------------------ attributes
    Route::resource('attributes', AttributeController::class)->except(['index', 'show']);

    // ------------------ spec types
    Route::get('spectypes/spec-type-data', [SpecTypeController::class, 'getData'])->name('spectypes.getdata');
    Route::get('spectypes/ajax/get', [SpecTypeController::class, 'ajax_get']);
    Route::resource('spectypes', SpecTypeController::class)->except(['show', 'create']);


    // ------------------ posts
    Route::resource('posts', PostController::class)->except(['show']);
    Route::get('post/categories', [PostController::class, 'categories'])->name('posts.categories.index');
    Route::post('post/slug', [PostController::class, 'generate_slug']);


    // ------------------ categories
    Route::resource('categories', CategoryController::class)->only(['update', 'destroy', 'store', 'edit']);
    Route::post('categories/sort', [CategoryController::class, 'sort']);
    Route::post('category/slug', [CategoryController::class, 'generate_slug']);


    // ------------------ pages
    Route::resource('pages', PageController::class)->except(['show']);

    // ------------------ menus
    Route::resource('menus', MenuController::class)->except(['edit']);
    Route::post('menus/sort', [MenuController::class, 'sort']);

    // ------------------ orders
    Route::resource('orders', OrderController::class)->only(['index', 'show', 'destroy']);
    Route::post('orders/{order}/shipping-status', [OrderController::class, 'shipping_status'])->name('orders.shipping-status');
    Route::post('orders/api/index', [OrderController::class, 'api_index']);

    // ------------------ shipping costs
    Route::resource('shipping-costs', ShippingCostController::class);

    // ------------------ transactions
    Route::resource('transactions', TransactionController::class)->only(['index', 'show', 'destroy']);

    // ------------------ sliders
    Route::resource('sliders', SliderController::class)->except(['show']);
    Route::post('sliders/sort', [SliderController::class, 'sort']);

    // ------------------ banners
    Route::resource('banners', BannerController::class)->except(['show']);
    Route::post('banners/sort', [BannerController::class, 'sort']);

    // ------------------ links
    Route::resource('links', LinkController::class)->except(['show']);
    Route::post('links/sort', [LinkController::class, 'sort']);
    Route::get('links/groups', [LinkController::class, 'groups'])->name('links.groups.index');
    Route::put('links/groups/update', [LinkController::class, 'updateGroups'])->name('links.groups.update');

    // ------------------ statistics
    Route::get('statistics/views', [StatisticsController::class, 'views'])->name('statistics.views');
    Route::get('statistics/viewers', [StatisticsController::class, 'viewers'])->name('statistics.viewers');

    // ------------------ contacts
    Route::resource('contacts', ContactController::class)->only(['index', 'show', 'destroy']);

    // ------------------ stock-notifies
    Route::resource('stock-notifies', StockNotifyController::class)->only(['index', 'show', 'destroy']);

    // ------------------ comments
    Route::resource('comments', CommentController::class)->only(['index', 'show', 'destroy', 'update']);

    // ------------------ roles
    Route::resource('roles', RoleController::class);

    // ------------------ permissions
    Route::get('permissions', [PermissionController::class, 'index'])->name('permissions.index');
    Route::put('permissions', [PermissionController::class, 'update'])->name('permissions.update');

    // ------------------ themes

app/Http/Controllers/Back/AttributeController.php
<?php

namespace App\Http\Controllers\Back;

use App\Models\Attribute;
use App\Models\AttributeGroup;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class AttributeController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(Attribute::class, 'attribute');
    }

    public function create()
    {
        $attributeGroups = AttributeGroup::all();

        return view('back.attributes.create', compact('attributeGroups'));
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'name'               => 'required',
            'attribute_group_id' => 'required|exists:attribute_groups,id'
        ]);

        Attribute::create([
            'name'                => $request->name,
            'value'               => $request->value,
            'attribute_group_id'  => $request->attribute_group_id,
        ]);

        toastr()->success('ویژگی با موفقیت ایجاد شد.');

        return response("success");
    }

    public function edit(Attribute $attribute)
    {
        $attributeGroups = AttributeGroup::all();

        return view('back.attributes.edit', compact('attribute', 'attributeGroups'));
    }

    public function update(Attribute $attribute, Request $request)
    {
        $this->validate($request, [
            'name'               => 'required',
            'attribute_group_id' => 'required|exists:attribute_groups,id'
        ]);

        $attribute->update([
            'name'                => $request->name,
            'value'               => $request->value,
            'attribute_group_id'  => $request->attribute_group_id,
        ]);

        toastr()->success('ویژگی با موفقیت ویرایش شد.');

        return response("success");
    }

    public function destroy(Attribute $attribute)
    {
        $attribute->delete();

        return response('success');
    }
}

app/Http/Controllers/Back/AttributeGroupController.php
<?php

namespace App\Http\Controllers\Back;

use App\Models\AttributeGroup;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class AttributeGroupController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(AttributeGroup::class, 'attributeGroup');
    }

    public function index()
    {
        $attributeGroups = AttributeGroup::orderBy('ordering')->get();

        return view('back.attributeGroups.index', compact('attributeGroups'));
    }

    public function attributesIndex(AttributeGroup $attributeGroup)
    {
        $attributes = $attributeGroup->get_attributes()->paginate(15);

        return view('back.attributes.index', compact('attributes'));
    }

    public function create()
    {
        return view('back.attributeGroups.create');
    }

    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'type' => 'required|in:color,checkbox',
        ]);

        $ordering = AttributeGroup::max('ordering') + 1;

        AttributeGroup::create([
            'name'       => $request->name,
            'type'       => $request->type,
            'ordering'   => $ordering
        ]);

        toastr()->success('گروه ویژگی با موفقیت ایجاد شد.');

        return response("success");
    }

    public function edit(AttributeGroup $attributeGroup)
    {
        return view('back.attributeGroups.edit', compact('attributeGroup'));
    }

    public function update(AttributeGroup $attributeGroup, Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'type' => 'required|in:color,checkbox',
        ]);

        $attributeGroup->update([
            'name'       => $request->name,
            'type'       => $request->type,
        ]);

        toastr()->success('گروه ویژگی با موفقیت ویرایش شد.');

        return response("success");
    }

    public function destroy(AttributeGroup $attributeGroup)
    {
        $attributeGroup->delete();

        return response('success');
    }

    public function sort(Request $request)
    {
        $this->authorize('attributes.groups.update');

        $this->validate($request, [
            'attributeGroups' => 'required|array'
        ]);

        $i = 1;

        foreach ($request->attributeGroups as $attributeGroup) {
            AttributeGroup::findOrFail($attributeGroup)->update([
                'ordering' => $i++,
            ]);
        };

        return response('success');
    }
}

app/Http/Controllers/Back/BackupController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\Controller;
use App\Jobs\CreateBackup;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class BackupController extends Controller
{
    public function index()
    {
        $this->authorize('backups.index');

        $backups = Storage::disk('backup')->allFiles(config('backup.backup.name'));

        foreach ($backups as $key => $backup) {
            $backups[$key] = [];
            $backups[$key]['date'] =  Storage::disk('backup')->lastModified($backup);
            $backups[$key]['name'] =  substr($backup, strrpos($backup, '/') + 1);
            $backups[$key]['size'] =  number_format(Storage::disk('backup')->size($backup) / 1048576, 2) . ' mb';
        }

        $backups = collect($backups);

        return view('back.backups.index', compact('backups'));
    }

    public function create()
    {
        $this->authorize('backups.create');

        CreateBackup::dispatchAfterResponse();

        return response('success');
    }

    public function download($backup)
    {
        $this->authorize('backups.download');

        $filename = config('backup.backup.name') . '/' . $backup;

        if (!Storage::disk('backup')->exists($filename)) {
            abort(404);
        }

        return Storage::disk('backup')->download($filename);
    }

    public function destroy($backup)
    {
        $this->authorize('backups.delete');

        $filename = config('backup.backup.name') . '/' . $backup;

        if (!Storage::disk('backup')->exists($filename)) {
            abort(404);
        }

        Storage::disk('backup')->delete($filename);
        return response('success');
    }
}

app/Http/Controllers/Back/CommentController.php
<?php

namespace App\Http\Controllers\Back;

use App\Models\Comment;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class CommentController extends Controller
{
    public function __construct()
    {
        $this->authorizeResource(Comment::class, 'comment');
    }

    public function index(Request $request)
    {
        $comments = Comment::filter($request)->paginate(15);

        return view('back.comments.index', compact('comments'));
    }

    public function show(Comment $comment)
    {
        return view('back.comments.show', compact('comment'))->render();
    }

    public function destroy(Comment $comment)
    {
        $comment->delete();

        return response('success');
    }

    public function update(Comment $comment, Request $request)
    {
        $this->validate($request, [
            'status' => 'required',
            'body'   => 'required',
            'replay' => 'nullable|string',
        ]);

        $comment->update([
            'body'   => $request->body,
            'status' => $request->status
        ]);

        if ($request->replay) {
            $comment->commentable->comments()->create([
                'body'       => $request->replay,
                'user_id'    => auth()->user()->id,
                'status'     => 'accepted',
                'comment_id' => $comment->id,
            ]);
        }

        return response($comment);
    }
}

resources/views/back/partials/banners.blade.php
@if($banners->count())
    <section class="card banners-sortable">
        <div class="card-header">
            <h4 class="card-title">{{ $title }}</h4>
        </div>
        <div class="card-content">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-striped mb-0">
                        <thead>
                            <tr>
                                <th class="text-center">ردیف</th>
                                <th>تصویر</th>
                                <th>عنوان</th>
                                <th class="text-center">وضعیت</th>
                                <th class="text-center">عملیات</th>
                            </tr>
                        </thead>
                        <tbody id="banners-sortable-{{ $loop->index }}">
                            @foreach($banners as $banner)
                                <tr id="banner-{{ $banner->id }}">
                                    <td class="text-center draggable-handler">
                                        <div class="fonticon-wrap"><i class="feather icon-move"></i></div>
                                    </td>
                                    <td>
                                        <div class="slider-thumb">
                                            <img src="{{ $banner->image }}" alt="banner image">
                                        </div>
                                    </td>
                                    <td>{{ $banner->title ?: '--' }}</td>
                                    <td class="text-center">
                                        @if($banner->published)
                                            <div class="badge badge-pill badge-success badge-md">منتشر شده</div>
                                        @else
                                            <div class="badge badge-pill badge-danger badge-md">پیش نویس</div>
                                        @endif
                                    </td>
                                    <td class="text-center">
                                        @can('banners.update')
                                            <a href="{{ route('admin.banners.edit', ['banner' => $banner]) }}" class="btn btn-info mr-1 waves-effect waves-light">ویرایش</a>
                                        @endcan

                                        @can('banners.delete')
                                            <button type="button" data-banner="{{ $banner->id }}" class="btn btn-danger mr-1 waves-effect waves-light btn-delete"  data-toggle="modal" data-target="#delete-modal">حذف</button>
                                        @endcan
                                        
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>
    
@else
    <section class="card">
        <div class="card-header">
            <h4 class="card-title">{{ $title }}</h4>
        </div>
        <div class="card-content">
            <div class="card-body">
                <div class="card-text">
                    <p>چیزی برای نمایش وجود ندارد!</p>
                </div>
            </div>
        </div>
    </section>
@endif

resources/views/back/partials/child_category.blade.php
<li class="dd-item" data-id="{{ $child_category->id }}">
    @if($child_category->categories->isEmpty())
        <div class="dd-handle"><span class="category-title">{{  $child_category->title  }}</span>
            <a data-category="{{ $child_category->slug }}" class="float-right delete-category dd-nodrag" href="javascript:void(0)"><i class="fa fa-trash text-danger px-1"></i>حذف</a>
            <a data-category="{{ $child_category->slug }}" class="float-right edit-category dd-nodrag" href="javascript:void(0)"><i class="fa fa-pencil text-info px-1"></i>ویرایش</a>
        </div>
    @else
        <div class="dd-handle"><span class="category-title">{{ $child_category->title }}</span>
            <a data-category="{{ $child_category->slug }}" class="float-right delete-category dd-nodrag" href="javascript:void(0)"><i class="fa fa-trash text-danger px-1"></i>حذف</a>
            <a data-category="{{ $child_category->slug }}" class="float-right edit-category dd-nodrag" href="javascript:void(0)"><i class="fa fa-pencil text-info px-1"></i>ویرایش</a>
        </div>
        <ol class="dd-list">
            @foreach ($child_category->childrenCategories as $childCategory)
                @include('back.partials.child_category', ['child_category' => $childCategory])
            @endforeach
        </ol>
    @endif
</li>

resources/views/back/partials/footer.blade.php
<footer class="footer footer-static footer-light">
    <p class="clearfix blue-grey lighten-2 mb-0"><span class="float-md-left d-block d-md-inline-block mt-25">کپی رایت &copy; {{ date('Y') }}<a class="text-bold-800 grey darken-2" href="https://ideal-it.ir" target="_blank">ایده آل آی تی,</a>تمامی حقوق محفوظ است</span><span class="float-md-right d-none d-md-block">طراحی و توسعه با <i class="feather icon-heart pink"></i>  توسط ایده آل آی تی</span>
    </p>
</footer>

resources/views/back/partials/header.blade.php
<div class="content-overlay"></div>
<div class="header-navbar-shadow"></div>
<nav class="header-navbar navbar-expand-lg navbar navbar-with-menu floating-nav navbar-light navbar-shadow">
    <div class="navbar-wrapper">
        <div class="navbar-container content">
            <div class="navbar-collapse" id="navbar-mobile">
                <div class="mr-auto float-left bookmark-wrapper d-flex align-items-center">
                    <ul class="nav navbar-nav">
                        <li class="nav-item mobile-menu d-xl-none mr-auto"><a
                                class="nav-link nav-menu-main menu-toggle hidden-xs" href="#"><i
                                    class="ficon feather icon-menu"></i></a></li>
                    </ul>

                </div>
                <ul class="nav navbar-nav float-right">

                    <li class="nav-item d-none d-lg-block"><a class="nav-link nav-link-expand"><i
                                class="ficon feather icon-maximize"></i></a></li>

                    @include('back.partials.notifications')
                    <li class="dropdown dropdown-user nav-item"><a class="dropdown-toggle nav-link dropdown-user-link"
                            href="#" data-toggle="dropdown">
                            <div class="user-nav d-sm-flex d-none"><span class="user-name text-bold-600">{{ auth()->user()->name }}</span></div><span><img class="round"
                                    src="{{ auth()->user()->imageUrl }}" alt="avatar"
                                    height="40" width="40"></span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right"><a class="dropdown-item" href="{{ route('admin.user.profile.show') }}"><i
                                    class="feather icon-user"></i> ویرایش پروفایل</a>
                            <div class="dropdown-divider"></div><a class="dropdown-item" href="{{ route('logout') }}"><i
                                    class="feather icon-power"></i> خروج</a>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</nav>

resources/views/back/partials/links.blade.php
@if($group->links->count())
    <section class="card links-sortable">
        <div class="card-header">
            <h4 class="card-title">{{ $group->title }}</h4>
        </div>
        <div class="card-content">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-striped mb-0">
                        <thead>
                            <tr>
                                <th class="text-center">ردیف</th>
                                <th>عنوان</th>
                                <th>لینک</th>
                                <th class="text-center">عملیات</th>
                            </tr>
                        </thead>
                        <tbody id="links-sortable-{{ $loop->index }}">
                            @foreach($group->links()->orderBy('ordering')->get() as $link)
                                <tr id="link-{{ $link->id }}">
                                    <td class="text-center draggable-handler">
                                        <div class="fonticon-wrap"><i class="feather icon-move"></i></div>
                                    </td>
                                    
                                    <td>{{ $link->title }}</td>
                                    <td>{{ $link->link }}</td>

                                    <td class="text-center">

                                        @can('links.update')
                                            <a href="{{ route('admin.links.edit', ['link' => $link]) }}" class="btn btn-info mr-1 waves-effect waves-light">ویرایش</a>
                                        @endcan

                                        @can('links.delete')
                                            <button type="button" data-link="{{ $link->id }}" class="btn btn-danger mr-1 waves-effect waves-light btn-delete"  data-toggle="modal" data-target="#delete-modal">حذف</button>
                                        @endcan
                                        
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>
    
@else
    <section class="card links-sortable">
        <div class="card-header">
            <h4 class="card-title">{{ $group->title }}</h4>
        </div>
        <div class="card-content">
            <div class="card-body">
                <div class="card-text">
                    <p>چیزی برای نمایش وجود ندارد!</p>
                </div>
            </div>
        </div>
    </section>
@endif

resources/views/back/partials/notifications.blade.php
<li class="dropdown dropdown-notification nav-item"><a class="nav-link nav-link-label" href="#"
        data-toggle="dropdown"><i class="ficon feather icon-bell"></i><span
            class="badge badge-pill badge-primary badge-up">{{ $notifications->count() ?: '' }}</span></a>
    <ul class="dropdown-menu dropdown-menu-media dropdown-menu-right">
        <li class="dropdown-menu-header">
            <div class="dropdown-header m-0 p-2">
                <h4 class="white">{{ $notifications->count() }} اعلان جدید</h4>
            </div>
        </li>
        <li class="scrollable-container media-list">
            @foreach ($notifications as $notification)
                @if($notification->type == 'App\Notifications\OrderPaid')

                    <a class="d-flex justify-content-between" href="{{ route('admin.notifications') }}">
                        <div class="media d-flex align-items-start">
                            <div class="media-left"><i class="feather icon-plus-square font-medium-5 primary"></i></div>
                            <div class="media-body">
                                <h6 class="primary media-heading">سفارش جدید ثبت شد</h6><small
                                    class="notification-text">{{ $notification->data['message'] }}</small>
                            </div><small>
                                <time class="media-meta">{{ tverta($notification->created_at)->formatDifference() }}</time></small>
                        </div>
                    </a>

                @elseif($notification->type == 'App\Notifications\UserRegistered')
                    <a class="d-flex justify-content-between" href="{{ route('admin.notifications') }}">
                        <div class="media d-flex align-items-start">
                            <div class="media-left"><i class="feather icon-user font-medium-5 success"></i></div>
                            <div class="media-body">
                                <h6 class="success media-heading">کاربر جدید ثبت نام کرد</h6><small
                                    class="notification-text">{{ $notification->data['message'] }}</small>
                            </div><small>
                                <time class="media-meta">{{ tverta($notification->created_at)->formatDifference() }}</time></small>
                        </div>
                    </a>

                @elseif($notification->type == 'App\Notifications\ContactCreated')
                    <a class="d-flex justify-content-between" href="{{ route('admin.notifications') }}">
                        <div class="media d-flex align-items-start">
                            <div class="media-left"><i class="feather icon-message-square font-medium-5 info"></i></div>
                            <div class="media-body">
                                <h6 class="info media-heading">پیام جدید دریافت شد</h6><small
                                    class="notification-text">{{ $notification->data['message'] }}</small>
                            </div><small>
                                <time class="media-meta">{{ tverta($notification->created_at)->formatDifference() }}</time></small>
                        </div>
                    </a>
                @endif
            @endforeach
        </li>
        <li class="dropdown-menu-footer">
            <a class="dropdown-item p-1 text-center" href="{{ route('admin.notifications') }}">نمایش همه اعلان ها</a>
        </li>
    </ul>
</li>